services:

  admin-app:
    container_name: admin-app
    build:
      context: admin-app
      dockerfile: Dockerfile
    image: admin-app:latest
    ports:
      - '3000:3000'
  customer-app:
    container_name: customer-app
    image: customer-app:latest
    build:
      context: customer-app
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
  
  back-end:
    container_name: back-end
    image: back-end:latest
    build:
      context: admin-app
      dockerfile: Dockerfile
    ports:
      - '8999:8999'
    environment:
      - 'MYSQL_DATABASE=clothingStore'
      # - 'MYSQL_PASSWORD=161200'
      - 'MYSQL_ROOT_PASSWORD=161200'
      - 'MYSQL_USER=hoangthh1612'
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=clothingStore'
      # - 'MYSQL_PASSWORD=161200'
      - 'MYSQL_ROOT_PASSWORD=161200'
      - 'MYSQL_USER=hoangthh1612'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: